- meta-phosphor/common/recipes-devtools/python/python-tftpy.bb
- meta-phosphor/common/recipes-phosphor/packagegroups/packagegroup-obmc-phosphor-apps.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton/make.patch
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton/skeleton.service
- meta-phosphor/common/recipes.txt
A pure python library for TFTP.
> Add recipe for https://github.com/msoulier/tftpy

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Update skeleton commit version in the recipe
Get executables from bin and libraries from lib
> Update skeleton version to pick up new executables

- meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf/machine/palmetto.conf
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-oem.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/conf/machine/include/sample.inc
Moved ipmi up to the latest level to allow the ipmid-api.h to be exported in the package
> Added liboemhandler.so to the official build

- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-bsp/u-boot/files/patch-2013.07/0001-u-boot-openbmc.patch
- meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-bsp/u-boot/files/u-boot-barreleye.patch
- meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-bsp/u-boot/u-boot_2013.07%.bbappend
- meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes.txt
turn off kernel debug messages (all systems)
Barreleye fix for network hang.
> uboot updates

- meta-phosphor/common/recipes-core/systemd/systemd/default.network
- meta-phosphor/common/recipes-core/systemd/systemd_%.bbappend
It just takes a basic config file to get systemd-networkd to pull and ip address.
> Enable DHCP

- meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb
removed the eventd program from the skeleton includes
Added DEPENDS per code review
> Adding real event log manager

- meta-phosphor/common/recipes-phosphor/host-ipmid/btbridged.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/btbridged/makefile.patch
It doesn't work inside OE at the moment.
> Patch btbridge makefile.

- meta-openbmc-machines/meta-openpower/conf/machine/include/openpower.inc
- meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf/machine/palmetto.conf
This was only being picked up on Palmetto.
> Use OEM parser on all OpenPOWER systems

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
During testing found a pnor locked problem
> move up skeleton for flash fix

- meta-openbmc-machines/meta-openpower/conf/machine/include/openpower.inc
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb
- meta-phosphor/conf/machine/include/sample.inc
> Add ipmi fru write to dbus

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Verified this works on Palmetto and QEMU
> Not all virtual sensors had properties

- meta-phosphor/common/recipes-core/os-release/os-release.bbappend
VERSION_ID = `git tag`
BUILD_ID = `git describe --dirty`
> Add git version information to os-release

- meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb
- meta-phosphor/common/recipes-phosphor/dbus/obmc-rest.bb
- meta-phosphor/common/recipes-phosphor/dbus/obmc-rest/obmc-rest.service
> update build to support rest features

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
This code reduces all ipmi connections to just 1
> Too many dbus connections

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Tested and verified this does work
> systems can power on without fans powering on

- meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
Brings in a fix for the GPIO interrupts.
> Update kernel version

- meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb
- meta-phosphor/common/recipes-phosphor/dbus/obmc-rest.bb
Fixes for freedesktop ObjectManager signal handling.
> Bump mapper and rest server revisions

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Updates include more sensors, reboot capabiltiies and so much more!
> Sprint 3 candidate 6

- meta-phosphor/common/recipes-phosphor/dbus/obmc-rest.bb
Needed for pending rest server authentication support.
> Add python-spwd depenency to rest server

- README.md
Small update to help people figure out what is needed to kick off the build process
> Added ubuntu dependencies to readme

- meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
> pflash and linux updates

- meta-phosphor/common/recipes-phosphor/host-ipmid/btbridged.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
c0448f0729f2eea6cf1160d3d6a723e2983a443e  Reset the OS power state when the system
3939e2d5752030e383efd37aa70f28a005fae7a0  Support for W25Q256BV flash chip module
7b8811e8d2d638046a000770ab88d4dfe6dcaee9  Added BMC_THROTTLE gpio and hwmon thermal sensor
> Pickup Sprint4 changes for skeleton

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
I pulled in the fix for the hconsole crashing after some time
> pulled in bugs fixes for sprint 4

- meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
Time for a move up.  Feature list can be found...
https://github.com/openbmc/linux/releases/tag/openbmc-20160120-1
> Moving up Linux

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
Merge pull request #58 from nkskjames/set_time
https://github.com/openbmc/phosphor-host-ipmid/commit/e90d8bf6a342649dba2fd1589a3cddb3cd051bb1
> Add fix for timeofday

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/common/recipes-phosphor/settings/settings.bb
- meta-phosphor/common/recipes-phosphor/settings/settings/settings.service
Create settings recipe and service files
Add dependency to settings to the ipmid recipe
since the upcoming ipmi boot flags use this
settings dbus object
> Add settings dbus object to openbmc image

- meta-phosphor/classes/obmc-phosphor-image_types_uboot.bbclass
Signed-off-by:  Norman James <nkskjames@gmail.com>
> add image-rwfs to flash tar

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Update skeleton recipe to pickup rwflash support
> Update skeleton recipe to pickup rwflash support

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Signed-off-by: Norman James <nkskjames@gmail.com>
> Move up skeleton commit and add libsystemd depends

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
- fix LED dependency so system will boot
Signed-off-by: Norman James <nkskjames@gmail.com>
> update skeleton commit

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
This fixes the issue #182 I was seeing
> Added systemd as build dependency for skeleton

- meta-phosphor/common/recipes-phosphor/dbus/obmc-rest.bb
Rest through the spec to see how to interact.
https://github.com/openbmc/docs/blob/master/rest-api.md
> Enable authentication over REST

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-oem.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Fixes memory leaks and watchdog timer issues
Signed-off-by: Norman James <nkskjames@gmail.com>
> Move up skeleton and host-ipmid to latest

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/common/recipes-phosphor/network/network.bb
- meta-phosphor/common/recipes-phosphor/obmc-phosphor-user/obmc-phosphor-user.bb
IPMI: Support for ipmitool lan high level commands
USER: User management fixes
> Update recipes to pick up IPMI and User management fixes

- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-bsp/u-boot/files/aspeednic-mac-stop.patch
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-bsp/u-boot/u-boot_2013.07%.bbappend
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc/0001-Fix-directory-hardlinks-from-deleted-directories.patch
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc/0001-Revert-jffs2-Fix-lock-acquisition-order-bug-in-jffs2.patch
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc/0001-Updated-SCU88-register-and-SCU90-init-values.patch
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc/0001-hwmon-power8_occ_i2c-Add-more-hwmon-sysfs-attribute-.patch
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc/0002-jffs2-Fix-page-lock-f-sem-deadlock.patch
- meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc_%.bbappend
- meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb
This request updates the kernel, boot loader, and the event logging application in the file system
to address issues encountered in testing.
Signed-off-by: Milton Miller <miltonm@us.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/213)
> Update kernel, u-boot, and eventd server

- meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash.bb
- meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0001-pflash-Allow-building-under-yocto.patch
- meta-openbmc-machines/meta-openpower/conf/layer.conf
- meta-openbmc-machines/meta-openpower/conf/machine/include/openpower.inc
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Fixes #103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/233)
> Use pflash from upstream skiboot instead of skeleton.

- meta-phosphor/conf/machine/include/obmc-bsp-common.inc
Build a rootfs cpio uimage with everything along with the other
images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/237)
> Build a tftpboot friendly image.

- meta-openbmc-machines/meta-openpower/common/recipes-phosphor/images/obmc-phosphor-image.bbappend
- meta-openbmc-machines/meta-openpower/common/recipes-phosphor/inventory-upload/inventory-upload.bb
- meta-openbmc-machines/meta-openpower/conf/layer.conf
- meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb
- meta-phosphor/common/recipes-phosphor/dbus/obmc-rest.bb
- meta-phosphor/common/recipes-phosphor/rest-dbus/rest-dbus.bb
- meta-phosphor/common/recipes-phosphor/skeleton/pyphosphor.bb
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/252)
> new recipes, version bumps supporting associations

- meta-openbmc-machines/meta-openpower/common/recipes-phosphor/inventory-upload/inventory-upload.bb
- meta-openbmc-machines/meta-openpower/common/recipes-phosphor/inventory-upload/inventory-upload/inventory-upload.service
- meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Bump mapper and skeleton versions.
Bump upload version and add systemd service file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/256)
> Bump versions for inventory upload

- meta-phosphor/common/recipes-phosphor/skeleton/pyphosphor.bb
This picks up a new enum for dbus - UnknownService.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/291)
> Bump pyphosphor version

- meta-openbmc-machines/meta-openpower/common/recipes-phosphor/inventory-upload/inventory-upload.bb
- meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-oem.bb
- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
- meta-phosphor/common/recipes-phosphor/settings/settings.bb
- meta-phosphor/common/recipes-phosphor/skeleton/pyphosphor.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Enable one-time vs permanent host boot option
Handle endianness in IPMI eSEL function
Improve IPMI error handling
Add IPMI Travis CI
Fix host hanging due to inventory upload
Performance improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/318)
> Bump phosphor recipe versions

- .gitignore
Change-Id: I958fb5d0d5cff35829b22b5d3e15e2d94356e62c
Signed-off-by: Rick Altherr <raltherr@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/331)
> Ignore build*, not just 'build'

- meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash.bb
- meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0007-external-Fix-ARM-build-failure-with-parallel-make.patch
This resolves https://github.com/openbmc/openbmc/issues/325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/402)
> Add pflash parallel build fix patch

- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/405)
> skeleton: update package to latest

- meta-phosphor/common/recipes-phosphor/skeleton/pyphosphor.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Closes openbmc/openbmc#218.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/406)
> Update skeleton and pyphosphor.

- meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-phosphor/workbook/barreleye-config.bb
- meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Pick up fixes and the ability to update at runtime and get the
bmc code update progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/454)
> Bump skeleton version for v1.0-stable

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
Pick up support for versioned libraries.
Closes openbmc/openbmc#423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/464)
> Bump IPMI version for v1.0-stable

- meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
Pick up support for versioned libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/465)
> Bump IPMI version

- meta-openbmc-machines/meta-openpower/meta-ibm/meta-firestone/recipes-phosphor/workbook/firestone-config.bb
- meta-openbmc-machines/meta-openpower/meta-ibm/meta-garrison/recipes-phosphor/workbook/garrison-config.bb
- meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/recipes-phosphor/workbook/palmetto-config.bb
- meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/workbook/witherspoon-config.bb
- meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-phosphor/workbook/barreleye-config.bb
- meta-phosphor/classes/config-in-skeleton.bbclass
- meta-phosphor/classes/skeleton-rev.bbclass
- meta-phosphor/classes/skeleton.bbclass
Reduce the number of files to be updated after a
skeleton update from two to one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/458)
> Add skeleton-rev class

- meta-phosphor/classes/obmc-phosphor-utils.bbclass
Four spaces for python code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/460)
> classes-utils: Whitespace fixes

- meta-phosphor/classes/obmc-phosphor-systemd.bbclass
A couple minor fixes to the systemd wrapper class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/463)
> classes-systemd: bug fix and best practices.

- meta-phosphor/common/recipes-devtools/python/python-ipy_0.83.bb
add ipy package for ip addressing validation
Signed-off-by: Edward A. James <eajames@us.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/468)
> python-ipy package
