meta-phosphor/common/recipes-connectivity/openssl/openssl_%.bbappend
Resolves openbmc/meta-phosphor#9.
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
=> openssl: reduce crypto algorithms used

meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf/bblayers.conf.sample
Choosing to cater to the superproject clone use case.
=> Palmetto template bblayers missing relocation

meta-phosphor/conf/distro/openbmc-phosphor.conf
5.2.0 is producing an unusable kernel for Palmetto.
Qemuarm seems to work fine on either 5.2.0 or 4.9.3.
Remove when https://github.com/openbmc/openbmc/issues/10 is resolved.
=> Back off GCC to 4.9.3

meta-openbmc-bsp/meta-aspeed/meta-ast2400/recipes-kernel/linux/linux-obmc_%.bbappend
Missing a 'file://' in linux-obmc SRC_URI
=> Fix build break

meta-phosphor/classes/kernel-cuimage.bbclass
The cuimage is used in the install task so it must be
generated by then.
=> Fix mkcimage task dependency in kernel-cuimage

meta-phosphor/conf/machine/include/sample.inc
btbridge is not even part of the qemu image
=> stop the build break for btbridge on qemu

meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf/layer.conf, meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf/machine/palmetto.conf, meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/recipes-kernel/linux/linux-obmc/palmetto.dts, meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/recipes-kernel/linux/linux-obmc_%.bbappend, meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/recipes.txt, meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/conf/machine/barreleye.conf, meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-kernel/linux/linux-obmc/barreleye.dts, meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-kernel/linux/linux-obmc_%.bbappend, meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes.txt, meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.2.bb
Add plumbing and initial device trees for Palmetto/Barreleye.
Bump kernel version.
=> Out of (kernel) tree device trees

yocto-poky/meta/recipes-core/dropbear/dropbear.inc, yocto-poky/meta/recipes-core/dropbear/dropbear/0010-stop-robot-test-SSHLibrary-from-hanging.patch
Dropbear last year added a change that breaks the SSHLibrary for
robot test framework.
Details about the problem...
https://github.com/robotframework/SSHLibrary/issues/128
The actual commit that caused the problem
https://github.com/mkj/dropbear/commit/ca86726f9f943b2b18e5694b442d3d2e1c0fa903
=> Enable robottest for ssh

README.md
This commit adds an image to the main openbmc GitHub page which shows the current build status, with a link to the Jenkins job.
=> add: build status on main page

meta-phosphor/common/recipes-core/os-release/os-release.bbappend
The existing version wasn't handling non-default build
directories or build from tarball (no git repository)
type setups.
=> os-release bug fixes

meta-phosphor/common/recipes-devtools/python/python-dbus/bytes.patch, meta-phosphor/common/recipes-devtools/python/python-dbus_1.2.0.bbappend
Byte to string simply copied the byte, which isn't valid
utf8 for non ascii values.  Since dbus.byte is an int subclass,
should just be using int's __str__  implementation anyway.
=> python-dbus dbus.Byte.__str__ produces broken utf8

meta-phosphor/common/recipes-core/os-release/os-release.bbappend
Use git-describe rather than git-tag.
Make os-release do_compile run every time.
=> os-release VERSION always points at v0.1

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
- Temporary AST setup for Palmetto and Barreleye
- Ensure all IP will be reset on reboot
These changes should help us to be less acceptable to userspace messing
up the configuration and causing bugs like the failure to reboot.
=> meta-phosphor: Update kernel to openbmc-20151210-1

meta-phosphor/common/recipes-core/dropbear/dropbear/dropbearkey.service, meta-phosphor/common/recipes-core/dropbear/dropbear_%.bbappend
Before this patch it isn't started until the first
client connection which is not the desired behavior.
=> Set dropbearkey service to start on boot

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-oem.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
Yocto's QA service identified issues with the build
The -fpic option was not included in .so files.
Resovles issue https://github.com/openbmc/openbmc/issues/105
=> Resolve relocation warnings with build

yocto-poky/meta/recipes-devtools/qemu/qemu.inc
Build of qemu-native on Ubuntu 15.10 fails on configure step.
The reason for this is that system dbus version is higher than
oe dbus version and system pulseaudio libraries require newer dbus.
It causes configure to break with a lot of errors similar to this:
libpulsecommon-6.0.so: undefined reference to dbus_watch_get_enabled@LIBDBUS_1_3
Fixed by building qemu-native with the system dbus on Ubuntu 15.10
Note: This is a workaround. It must be removed when oe dbus is upgraded
to the version >= system dbus version (1.10.0 at the moment).
[YOCTO #8553]
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Signed-off-by: Ed Bartosh <ed.bartosh@linux.intel.com>
=> qemu-native: fix build on Ubuntu 15.10

meta-phosphor/common/recipes-core/systemd/systemd_%.bbappend
This is a workaround for issue:
https://github.com/openbmc/openbmc/issues/152
Once the issue is resolved, this workaround can be removed.
=> Add workaround to avoid disabling serial console

meta-phosphor/classes/obmc-phosphor-image_types_uboot.bbclass
Creates 2 tarballs.  The file names match the /proc/mtd partition names.
1. Contains full flash image (image-bmc)
2. Contains image-u-boot, image-kernel, image-rofs, and image-initramfs
Signed-off-by: Norman James <nkskjames@gmail.com>
=> Create tarball of update files with correct names

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/network/network.bb, meta-phosphor/common/recipes-phosphor/network/network/network.service
Create networkd recipe and service files
Add dependency to networkd to the ipmid recipe
since the upcoming ipmi set/get lan ipmi cmds will
make use of the network dbus object
=> Add network dbus object to openbmc image

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
Move to openbmc-20160202-2. Between -1 and -2, we get the following:
- Stable release 4.3.5
- Only impact for us are some fixes for the core networking layer
- First pass of VUART patches from Jeremy
- Build fix for the OCC hwmon driver
- Locking fixes for ncsi and i2c
=> meta-phosphor: Update kernel version

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/network/network.bb, meta-phosphor/common/recipes-phosphor/settings/settings.bb, meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Update openbmc phosphor recipes to pickup latest functionality from
skeleton, ipmi, networkd, settings, etc.
=> Update phosphor recipes to pickup latest code

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/network/network.bb, meta-phosphor/common/recipes-phosphor/network/network/80-dhcp.network
Backout kernel level since tag 20160202 has vuart support that bmc
currently does not support
Pickup IPMI and REST functions to update the MAC address
Remove dhcp file from network recipe that seems to cause issues
Update skeleton with syntax fix
=> Update recipes and remove dhcp file

meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-init.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-shutdown.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-update.sh
This series of patches to the obmc init, shutdown, and update scripts adds several features, including
Run fsck on the read write filesystem before mounting.
More information on what to do and options when init fails
Consistent location of update images even during init repair cases
Plus these developer features
All mount arguments consolidated into variables
Clean unmount when testing rofs image in RAM (from the /run file system)
Other clean ups
This version splits the first commit into 3 changes, and updates the messages to have more whitespace and a more explicit statement of the chroot test along with commit message edits.
It corrects a missed variable conversion of rwdir in update and loops on the chroot test.
=> Initfs fsck v3

meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb
Making a very simple commit that contains the additional required
c++ flags along with making the directory to store the new event
manager log files.  This does not enable anything, it is a
precursor got the big drop.  I'd like to get some of the more
simple things in to the build first since a 2 line change is
faster to review.
=> Prep work for presistent event logs

meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/whitelist
Enable the /var/lib/obmc/events in the whitelist
Move pointers up for event manager and object manager
=> Enable Persistent event logs in OBMC

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
- vuart driver fix
- i2c name fix
- led names and polarity fixes
=> meta-phosphor: Bump kernel to 20160211-1

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
Fixes in serial/aspeed-vuart:
- Perform enable/disable on driver bind/unbind
- Only disable host tx discard when serial port is in use
Plus a small device tree fix from Milton.
=> meta-phosphor: Bump kernel to 20160212-1

meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Update skeleton recipe to pick up persistent UUID support
by using the system uuid.
=> Update skeleton recipe to pick up persistent UUID support

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.3.bb
- 4.3.6 stable release
- mtd: spi-nor: aspeed-smc: Use io string accessors to fifo
- i2c: aspeed: Don't rename added devices
- Remove GPIO and LPC from WDT reset list
=> meta-phosphor: Update Linux to openbmc-20160222-1

meta-phosphor/classes/image-overlay.bbclass, meta-phosphor/classes/obmc-phosphor-image_types_uboot.bbclass, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-init.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-shutdown.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-update.sh
This series updates the build and init scripts to allow, nee require, that the rwfs be a jffs2 instead of our former ext4 filesystem.  
An kernel command line parameter clean-rwfs-filesystem, is also detected to clean the filesystem back to the whitelisted files.
The init and update scripts now use blkid to detect known filesystems, and assume jffs2 if blkid produces no output (as there is no current probe for jffs2).  The erased nor is also considered jffs2 and the kernel is happy to mount and use such a flash partition.
The requirement can be turned off with a 1 word edit to a flag in the init script.  Another flag can be
set to allow images to be built into an initrd for netboot updating.  Images can also be downloaded at the debug-init-sh sulogin shell if that is set in the command …
=> Change Read/Write overlay filesystem to jffs2

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-oem.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb
You will now get all the debug data in the event logs.  This was different
then in the past as there was a fixed few bytes of meaningless information.
The feature also reduces the memory footprint of the event manager AND
removes eselxxx logs in /tmp
=> Integrating support for event log enhancements

meta-phosphor/common/recipes-phosphor/inarp/inarp.bb, meta-phosphor/common/recipes-phosphor/inarp/inarp/inarp.service
This change adds 'inarp': A small daemon to listen for, and reply to
inverse ARP requests.
This should be started at system init time, so we add a .service file.
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
=> inarp: Add inverse ARP daemon

meta-phosphor/classes/obmc-phosphor-image.bbclass
Add the inarp package to the base image. If users later want
to turn it off and not have it be part of the base image,
it can be changed to a distro spec then.
=> Add inarp to base image

meta-phosphor/common/recipes-bsp/u-boot/u-boot-fw-utils_2013.07.bb, meta-phosphor/common/recipes-bsp/u-boot/u-boot_2013.07.bb
Change the u-boot recipes from picking up the most recent
commit to a specific commit (the most current one a of today)
so that development can be done in u-boot without affecting the
stability of the image.
=> Use commit number instead of autorev for u-boot

meta-phosphor/common/recipes-phosphor/clear-once/clear-once.bb, meta-phosphor/common/recipes-phosphor/clear-once/clear-once/clear-once.service, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid/host-ipmid.service, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-init.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-shutdown.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-update.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/obmc-phosphor-init.bb
This series adds support to the openbmc phosphor initfs scripts to support the BMC running with either or both of the read-write and read-only layers of the root file system to be in RAM instead of in the flash.
This decision is made via u-boot firmware variables and the kernel command line, and is designed to have a persistent and one time option.
Also included is a systemd service called clear-once that clears the variable meant for one time use.  The host-ipmid service is modified to want to run after the clear-once service in anticipation of the a OEM command that will set the variable.
When running in RAM the read-write layer can be replaced with updated content.  If both layers are in memory the BMC will not be accessing the flash except by explicit action, which include a shutdown …
=> Update openbmc initfs to add temporary run from RAM 

meta-phosphor/common/recipes-phosphor/inarp/inarp.bb
This change updates us to 19ed5170, which supports dynamic interface
configuration, and better syslog support.
Jeremy Kerr (3):
Rename inarp_ctx.socket
Use netlink for link state queries
Use syslog for log output
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/211)
=> inarp: Update to 19ed5170

meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/files/obmc-phosphor-event.service
The event log process now supports an argument to specify the max
size of the event log db. Set this size to a default of 200kB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/214)
=> Limit size of event log db

meta-phosphor/classes/obmc-phosphor-image.bbclass, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console.bb, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console/obmc-console.conf, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console/obmc-console.service
This change introduces obmc-console, a little daemon to handle the UART
data and multiplex it to a log and client processes.
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/215)
=> Add obmc-console project

meta-phosphor/classes/obmc-phosphor-image.bbclass, meta-phosphor/common/recipes-core/dropbear/dropbear/0001-dropbear-Add-c-command-option-to-force-a-specific-co.patch, meta-phosphor/common/recipes-core/dropbear/dropbear_%.bbappend, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console.bb, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console/obmc-console-ssh.socket, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console/obmc-console-ssh@.service
Following the previous disable, this bumps us to a working obmc-console version, and adds infrastructure for a ssh-based remote console connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/232)
=> Re-enable obmc-console and add a ssh endpoint

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/network/network.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb, meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Add release version id to inventory and IPMI interface
Add REST interface to query the type of network interface
Add event REST association suppot
Fix inventory data for CPU1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/251)
=> Recipe updates for Network, Skeleton, Event, IPMI

meta-phosphor/common/recipes-core/os-release/os-release.bbappend
Currently VERSION_ID is v0.6
Even when I am 30 commits past the tag.  I am swapping the code's BUILD/VERSION populator
to ensure we adhere to the reason why VERSION_ID exists in the first place... to know what
level of code you have on the system
Definition of what the VERSION_ID is for...
https://www.freedesktop.org/software/systemd/man/os-release.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/253)
=> VERSION_ID is not granular

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb
Adding https://github.com/openbmc/phosphor-host-ipmid/commit/176c96534484213dfb19d2ef5f70306b145a4fcf
to all the ipmi -I dbus mc info command to reflect what is seen via REST
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/254)
=> Add version_id support in to openbmc

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.4.bb
- Update to 4.4.9 for security and bug fixes
- Adds device tree and network phy for firestone support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/255)
=> meta-phosphor: Move to openbmc-20160505-1

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.4.bb
- Enables network cable link detection
- Adds support for VOUT sampling to the adm1275 driver
Fixes https://github.com/openbmc/linux/issues/71 and https://github.com/openbmc/linux/issues/61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/270)
=> meta-phosphor: Move to openbmc-20160511-1

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.4.bb
- Add EEPROM to barreleye device tree
- Update to 4.4.10 stable release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/277)
=> meta-phosphor: Move to openbmc-20160518-1

meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb, meta-phosphor/common/recipes-phosphor/obmc-console/obmc-console.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/files/obmc-phosphor-event.service, meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb
Updates for:
Console - Support for local tty mirroring
Object manager - BMC boot performance improvements
Event logs - Cap the number of event logs at 128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/279)
=> Bump version for console, object manager, and event logs

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.4.bb
- Enable shmem in config, fixing qemu bootin
- Add latest version of Yi's OCC hwmon driver to support barreleye
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/294)
=> Release openbmc-20160521-1

meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Fix OCC hardcoded sensor
Add adm1278 sensors
Fix preserving u-boot env variables during BMC updates
Add gpio Q7 handling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/301)
=> Bump skeleton version

meta-phosphor/common/recipes-bsp/u-boot/u-boot_2013.07.bb
This commit updates u-boot to include the long term fix to not leave the ethernet controller running when the network is not used to boot the kernel.
An intermediate fix to u-boot was applied in the v0.6-stable branch in commit 8e5dd42060cd8e293d2b8d45c62a1c5f143ba988 via #213.  The final fixes were later commited to openbmc/u-boot@fecb84ab7f3bddc4039b5de31f57440e1cfff650 but the pull request to update openbmc to use the fix #227 was stalled because of unrelated changes to pick up a new compiler which may still have issues with other code.  The additional fixes in u-boot allow both the old and new compiler to be used but the compiler is not changed in this pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> Update u-boot to pick up memory corruption fix

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmi-hw-example.bb
AUTOREV assumes you can reach the remote repository to lookup the most
recent commit.  When setting up a hermetic build, that will fail even
though a local mirror tarball exists.  Pinning the recipe to a specific
revision skips the lookup and just checks out the specified commit from
the local mirror tarball.
Change-Id: I05cfa67dfcd321ff28a93453df5ce1c82666e6c1
Signed-off-by: Rick Altherr <raltherr@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/308)
=> Pin host-ipmi-hw-example to a specific Git SRCREV

meta-phosphor/common/recipes-devtools/i2c-tools/i2c-tools_%.bbappend
Override syntax (FOO_append, FOO_prepend) doesn't insert spaces to
separate the append from the original value.  This caused the two URIs
to be incorrectly merged into one and caused a download failure.  It
happens that the fallback in that case is to use the Yocto mirror so it
kept working other than emitting a warning.  Using =+ prepend syntax
correctly adds the separating space.
Signed-off-by: Rick Altherr <raltherr@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/305)
=> Fix i2c-tools SRCURI syntax

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.4.bb
This snippet was mistakenly removed with 8ef9fee.
Note that this isn't a matter of policy, it simply enables
the option to do it.  The in-tree device tree is still the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/275)
=> Re-enable out of tree device trees

meta-phosphor/common/recipes-kernel/linux/linux-obmc_4.4.bb
- Stable release 4.4.12
- Jeremy's i2c completion fix
- Ken's power button debounce code for Barreleye
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/313)
=> meta-phosphor: Move to openbmc-20160606-1

meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash.bb, meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0001-Make-links-target-reusable.patch, meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0002-external-Remove-external-shared-link-targets.patch, meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0003-external-Fix-pflash-install-target.patch, meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0004-external-Remove-m64-from-shared-CFLAGS-on-ARM.patch, meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0005-external-Create-shared-rules.mk.patch, meta-openbmc-machines/meta-openpower/common/recipes-bsp/pflash/pflash/0006-external-Add-dynamically-linked-pflash.patch
Move to pflash 5.2.2.
Pick up a couple patches that allow building a shared library
and dynamically linked pflash binary.
Add pflash to SDK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/316)
=> Bump pflash version

meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper/obmc-mapper.service, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/skeleton/pyphosphor.bb
This picks up a couple fixes that addresses non-standard DBUS naming
conventions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/369)
=> Bump pyphosphor, host-ipmid versions

meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb
OE packaging works best with libraries with proper versioning.  This patchest picks up a change in host-ipmid-fru that enables versioning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/326)
=> Add shared library versioning for host-ipmid-fru

meta-phosphor/classes/config-in-skeleton.bbclass, meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Skeleton now invokes python setuptools to install its python
applications in a top level makefile, so a build time dependency
on native-python is required.
It should be noted that skeleton invoking python from make is
an interim thing until its python applications get their own
repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/371)
=> Add build time dependencies to python for skeleton

meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/conf/local.conf.sample, meta-phosphor/classes/obmc-phosphor-image.bbclass, meta-phosphor/common/recipes-phosphor/packagegroups/packagegroup-obmc-phosphor-apps.bb
Remove the rest-dbus development debug package from Barreleye now that Barreleye is going into production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/379)
=> Remove rest-dbus from Barreleye

meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/recipes-phosphor/workbook/palmetto-config.bb, meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/recipes-phosphor/workbook/barreleye-config.bb, meta-phosphor/common/recipes-phosphor/dbus/obmc-rest.bb, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid-fru.bb, meta-phosphor/common/recipes-phosphor/inarp/inarp.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/obmc-phosphor-event.bb, meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Bump recipe versions and add python dependencies.
The rest-dbus recipe was adding pythong packages needed
by other processes, so when rest-dbus was removed from the
Barreleye image, these processes (skeleton and obmc-rest)
would fail, so adding the python dependencies to those recipes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/393)
=> Bump versions for skeleton, rest, inarp, event

meta-phosphor/common/recipes-phosphor/network/network.bb, meta-phosphor/common/recipes-phosphor/network/network/network-update-dns.service
Commit c69c3d3 for phosphor-netword introduced DNS support.
This change will update the bitbake file to point to correct commit
and also creates the service file to start DNS updater.
Fixes openbmc/openbmc#134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/394)
=> Update recipe and service file for phosphor-networkd

meta-phosphor/common/recipes-phosphor/network/network/network.service, meta-phosphor/common/recipes-phosphor/settings/settings/settings.service
The network and settings daemons had unnecessary startup dependencies
on the skeleton service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/403)
=> Remove unnecessary skeleton dependencies

meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper.bb, meta-phosphor/common/recipes-phosphor/dbus/obmc-mapper/obmc-mapper.service, meta-phosphor/common/recipes-phosphor/host-ipmid/host-ipmid.bb, meta-phosphor/common/recipes-phosphor/skeleton/skeleton.bb
Pick changes for:
Encoding firmware version in BCD format
Handle floating point sensor values
Performance improvements
Extend the mapper service startup timeout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/414)
=> Bump versions for skeleton, IPMI, obmc-mapper

yocto-poky/meta/recipes-devtools/rpm/rpm_5.4.16.bb
Configure autodetects libtomcrypt, but then it adds libtommath to
$LIBS and fails to link subsequent tests if it's unavailable.
| checking for pcre.h... yes
| checking for pcre_compile in -lpcre... no
| checking whether to build with PCRE library... no
| ++ executing failure action
| configure: error: unable to find usable PCRE library
(From OE-Core rev: 54665fb9e27ba1b0e4eddaf170303d4f2db66fae)
Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/424)
=> rpm: explicitly disable tomcrypt

meta-phosphor/classes/obmc-phosphor-image_types_uboot.bbclass, meta-phosphor/classes/obmc-phosphor-initfs.bbclass, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-init.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-shutdown.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-update.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/whitelist, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/obmc-phosphor-initfs.bb
The underlying storage for a file system can not be updated when it is in use.  The initial solution was to update the flash as the system was being shutdown, with output to the console.
Updates were made to the `init` script that allows the flash to not be used for a given boot but the `update` script was not updated for error handling, and no documentation was provided to prepare the system for this mode.
When combined with openbmc/skeleton#111 this series is intended to address #293 by providing for the flash to be written while running the full stack after a `PrepareForFlash` mode has been initiated.
This also has fixes for saving files fixing #378.
These are the changes in #297 applied to the v1.0-stable branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Update flash update to be useable at runtime for v1.0-stable

meta-phosphor/classes/obmc-phosphor-image_types_uboot.bbclass, meta-phosphor/classes/obmc-phosphor-initfs.bbclass, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-init.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-shutdown.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/obmc-update.sh, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/files/whitelist, meta-phosphor/common/recipes-phosphor/obmc-phosphor-initfs/obmc-phosphor-initfs.bb
The underlying storage for a file system can not be updated when it is in use.  The initial solution was to update the flash as the system was being shutdown, with output to the console.
Updates were made to the init script that allows the flash to not be used for a given boot but the update script was not enhanced to make this user friendly, and no documentation was provided to prepare the system for this mode.
This series partially addresses #293 by enhancing the update script to
1. provide more fine grained checks on update conflicts allowing use at runtime
2. provide additional checks that would cause failure to flash
3. provide user help and consistent tagging of error output
4. provide an error return code if the checks fail
5. provide a nice diagnostic if no images were presented …
=> Update flash update to be useable at runtime.

meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-kernel/linux/linux-obmc_4.7.bb
This enables all of the i2c buses that are present in the hardware.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/456)
=> meta-witherspoon: Bump kernel version

meta-phosphor/common/recipes-phosphor/obmc-phosphor-flash/obmc-flash-bmc.bb
A couple new python modules were added to bmc_update.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/459)
=> Add some missing dependencies to obmc-flash-bmc

meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-pydbus/files/obmc-phosphor-example-pydbus.py, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-pydbus/files/org.openbmc.examples.PythonService.conf, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-pydbus/files/org.openbmc.examples.PythonService0.conf, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-pydbus/files/pyclient-sample.py, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-pydbus/obmc-phosphor-example-pydbus.bb, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-sdbus/files/obmc-phosphor-example-sdbus.c, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-sdbus/files/org.openbmc.examples.SDBusService.conf, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-sdbus/files/org.openbmc.examples.SDBusService1.conf, meta-phosphor/common/recipes-phosphor/obmc-phosphor-example-sdbus/obmc-phosphor-example-sdbus.bb
I can't think of any use cases for this.  Removing to make things less confusing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/461)
=> Remove extra busses from python and sdbus examples

meta-phosphor/common/recipes-core/systemd/systemd/obmc-standby.target, meta-phosphor/common/recipes-core/systemd/systemd_%.bbappend
Add a target pulled in by multi-user to which Phosphor applications
can be added.  This is an organizational change only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/462)
=> systemd: Add OpenBMC standby target

meta-phosphor/conf/distro/openbmc-phosphor.conf
This is the oldest kernel currently used by openbmc, so there is no
point in compiling glibc support older kernels.
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openbmc/openbmc/425)
=> Force OLDEST_KERNEL to 4.4.0
